"""
Custom Trading Strategies
Auto-generated by the Strategy Builder in dashboard.py
Add your custom strategy classes here - they will automatically appear in the dropdown!
"""

import pandas as pd
import numpy as np
import pandas_ta_classic as ta
import logging
from typing import Optional, Dict
import config

logger = logging.getLogger(__name__)


# Your custom strategies will be appended below this line
# ============================================================================












class MacdOnlyStrategy:
    """
    macd only - Custom Strategy
    Auto-generated by Strategy Builder
    """

    @staticmethod
    def get_optimizable_params():
        return {
            "MACD": {
                "name": "macd",
                "type": "float",
                "min": 1,
                "max": 100,
                "step": 1,
                "default": 30,
                "optimize_min": 1,
                "optimize_max": 100,
                "optimize_step": 5,
                "description": "Primary optimization parameter"
            }
        }

    @staticmethod
    def generate_vectorized_signals(close, high, low, volume, param_ranges):
        T = len(close)
        threshold_range = param_ranges.get('MACD', np.array([30]))
        N = len(threshold_range)
        macd_data = ta.macd(close)
        macd_line = macd_data.iloc[:, 0].values[:, None]
        macd_sig = macd_data.iloc[:, 1].values[:, None]
        entries = np.tile(macd_line < macd_sig, (1, N))
        entries = np.asarray(entries, dtype=bool)
        exits = ~entries
        zeros = np.zeros_like(entries)
        return {
            'long_entries': entries,
            'long_exits': exits,
            'short_entries': zeros,
            'short_exits': zeros,
            'param_columns': {'macd': threshold_range},
        }

    def __init__(self, **kwargs):
        self.rsi_period = 14
        self.macd = kwargs.get('MACD', 30)
        logger.info(f"MacdOnlyStrategy initialized")

    def calculate_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()

        # Calculate MACD
        if "MACD" == "RSI":
            df['RSI'] = ta.rsi(df['Close'], length=self.rsi_period)
        elif "MACD" == "MACD":
            macd = ta.macd(df['Close'])
            df['MACD'] = macd.iloc[:, 0]
            df['MACD_Signal'] = macd.iloc[:, 1]
        elif "MACD" == "SMA_Cross":
            df['SMA_20'] = ta.sma(df['Close'], length=20)
            df['SMA_50'] = ta.sma(df['Close'], length=50)
        elif "MACD" == "EMA_Trend":
            df['EMA_20'] = ta.ema(df['Close'], length=20)
        elif "MACD" == "Volume_Spike":
            df['Volume_SMA'] = ta.sma(df['Volume'], length=20)
            df['Volume_Ratio'] = df['Volume'] / df['Volume_SMA']

        return df

    def check_hard_filters(self, row: pd.Series) -> bool:
        try:
            # Rule 1: MACD < 30.0
            if "MACD" == "RSI":
                condition1 = row['RSI'] < 30.0
            elif "MACD" == "MACD":
                condition1 = row['MACD'] < row['MACD_Signal']
            elif "MACD" == "SMA_Cross":
                condition1 = row['SMA_20'] < row['SMA_50']
            elif "MACD" == "EMA_Trend":
                condition1 = row['Close'] < row['EMA_20']
            elif "MACD" == "Volume_Spike":
                condition1 = row['Volume_Ratio'] < 0.3
            else:
                condition1 = True

            # Rule 2 (optional)
            condition2 = True

            passed = condition1 and condition2

            if passed:
                logger.info(f"MacdOnlyStrategy filters PASSED")

            return passed

        except Exception as e:
            logger.error(f"Error in MacdOnlyStrategy filter: {e}")
            return False

    def generate_prompt(self, row: pd.Series, lookback_rows: Optional[pd.DataFrame] = None) -> str:
        return f"""Symbol: {config.TICKER}
Price: ${row['Close']:.2f}
Strategy: macd only

This is a custom strategy. Analyze the setup and decide BUY or HOLD.
"""

    def get_position_size(self, price: float, account_value: float) -> int:
        dollar_amount = min(config.POSITION_SIZE, account_value * 0.95)
        return max(1, int(dollar_amount / price))


class RsiMacdStrategy:
    """
    rsi + macd - Custom Strategy
    Auto-generated by Strategy Builder
    """

    @staticmethod
    def get_optimizable_params():
        return {
            "rsi": {
                "name": "rsi threshold",
                "type": "float",
                "min": 5,
                "max": 95,
                "step": 1,
                "default": 30,
                "optimize_min": 5,
                "optimize_max": 95,
                "optimize_step": 5,
                "description": "Primary optimization parameter"
            }
        }

    @staticmethod
    def generate_vectorized_signals(close, high, low, volume, param_ranges):
        import numpy as np
        T = len(close)
        param_key = "rsi"
        threshold_range = param_ranges.get(param_key, np.array([30]))
        N = len(threshold_range)

        if "RSI" == "RSI":
            rsi = ta.rsi(close, length=14)
            ind_vals = rsi.values[:, None]
            entries = ind_vals < threshold_range
        elif "RSI" == "MACD":
            macd_data = ta.macd(close)
            macd_line = macd_data.iloc[:, 0].values[:, None]
            macd_sig = macd_data.iloc[:, 1].values[:, None]
            entries = np.tile(macd_line < macd_sig, (1, N))
        elif "RSI" == "SMA_Cross":
            sma20 = ta.sma(close, length=20).values[:, None]
            sma50 = ta.sma(close, length=50).values[:, None]
            entries = np.tile(sma20 < sma50, (1, N))
        elif "RSI" == "EMA_Trend":
            ema20 = ta.ema(close, length=20).values[:, None]
            close_vals = close.values[:, None]
            entries = np.tile(close_vals < ema20, (1, N))
        elif "RSI" == "Volume_Spike":
            vol_sma = ta.sma(volume, length=20)
            vol_ratio = (volume / vol_sma).values[:, None]
            entries = vol_ratio < (threshold_range / 100.0)
        else:
            entries = np.zeros((T, N), dtype=bool)

        entries = np.asarray(entries, dtype=bool)
        exits = ~entries
        zeros = np.zeros_like(entries)
        return {
            'long_entries': entries,
            'long_exits': exits,
            'short_entries': zeros,
            'short_exits': zeros,
            'param_columns': {'rsi threshold': threshold_range},
        }

    def __init__(self, **kwargs):
        self.rsi_period = 14
        self.rsi = kwargs.get('rsi', 30)
        logger.info(f"RsiMacdStrategy initialized")

    def calculate_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()

        # Calculate RSI
        if "RSI" == "RSI":
            df['RSI'] = ta.rsi(df['Close'], length=self.rsi_period)
        elif "RSI" == "MACD":
            macd = ta.macd(df['Close'])
            df['MACD'] = macd.iloc[:, 0]
            df['MACD_Signal'] = macd.iloc[:, 1]
        elif "RSI" == "SMA_Cross":
            df['SMA_20'] = ta.sma(df['Close'], length=20)
            df['SMA_50'] = ta.sma(df['Close'], length=50)
        elif "RSI" == "EMA_Trend":
            df['EMA_20'] = ta.ema(df['Close'], length=20)
        elif "RSI" == "Volume_Spike":
            df['Volume_SMA'] = ta.sma(df['Volume'], length=20)
            df['Volume_Ratio'] = df['Volume'] / df['Volume_SMA']

        return df

    def check_hard_filters(self, row: pd.Series) -> bool:
        try:
            # Rule 1: RSI < 30.0
            if "RSI" == "RSI":
                condition1 = row['RSI'] < 30.0
            elif "RSI" == "MACD":
                condition1 = row['MACD'] < row['MACD_Signal']
            elif "RSI" == "SMA_Cross":
                condition1 = row['SMA_20'] < row['SMA_50']
            elif "RSI" == "EMA_Trend":
                condition1 = row['Close'] < row['EMA_20']
            elif "RSI" == "Volume_Spike":
                condition1 = row['Volume_Ratio'] < 0.3
            else:
                condition1 = True

            # Rule 2 (optional)
            condition2 = True

            passed = condition1 and condition2

            if passed:
                logger.info(f"✓ RsiMacdStrategy filters PASSED")

            return passed

        except Exception as e:
            logger.error(f"Error in RsiMacdStrategy filter: {e}")
            return False

    def generate_prompt(self, row: pd.Series, lookback_rows: Optional[pd.DataFrame] = None) -> str:
        return f"""Symbol: {config.TICKER}
Price: ${row['Close']:.2f}
Strategy: rsi + macd

This is a custom strategy. Analyze the setup and decide BUY or HOLD.
"""

    def get_position_size(self, price: float, account_value: float) -> int:
        dollar_amount = min(config.POSITION_SIZE, account_value * 0.95)
        return max(1, int(dollar_amount / price))
